name: SGVL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cudatoolkit=11.3.1=h9edb442_11
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=hca18f0e_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - icu=70.1=h27087fc_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libhwloc=2.8.0=h32351e8_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.8=h0b41bf4_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=23.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=3_cp39
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h0f457ee_0
  - scikit-learn=1.2.2=py39h86b2a18_0
  - setuptools=67.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tbb=2021.7.0=h924138e_1
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.0=py39_cu113
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - attrs==22.2.0
    - blis==0.7.9
    - braceexpand==0.1.7
    - catalogue==2.0.8
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - click==8.1.3
    - confection==0.0.4
    - cymem==2.0.7
    - datasets==2.9.0
    - decord==0.6.0
    - dill==0.3.6
    - easydict==1.10
    - einops==0.6.1
    - fairscale==0.4.4
    - filelock==3.9.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - huggingface-hub==0.12.0
    - idna==3.4
    - iopath==0.1.10
    - jinja2==3.1.2
    - kaleido==0.2.1
    - langcodes==3.3.0
    - markupsafe==2.1.2
    - multidict==6.0.4
    - multiprocess==0.70.14
    - murmurhash==1.0.9
    - nltk==3.8.1
    - omegaconf==2.3.0
    - opencv-python==4.7.0.68
    - packaging==23.0
    - pandas==1.5.3
    - pathy==0.10.1
    - plotly==5.13.1
    - portalocker==2.7.0
    - preshed==3.0.8
    - pyarrow==11.0.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.6
    - pydantic==1.10.6
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - responses==0.18.0
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - sacremoses==0.0.53
    - scipy==1.10.0
    - smart-open==6.3.0
    - spacy==3.5.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - tenacity==8.2.2
    - thinc==8.1.9
    - timm==0.4.12
    - tokenizers==0.10.3
    - tqdm==4.64.1
    - transformers==4.15.0
    - typer==0.7.0
    - urllib3==1.26.14
    - wasabi==1.1.1
    - webdataset==0.2.31
    - xxhash==3.2.0
    - yarl==1.8.2
prefix:
